# fly.toml app configuration file generated for backend-mellowed-shoreline-1360 on 2026-06-02T01:28:19+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-mellowed-shoreline-1360'
primary_region = 'lhr'

[build]
  [build.args]
    GO_VERSION = '1.26.3'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[deploy]
  strategy = 'immediate'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[[mounts]]
  source = 'bidding_data'
  destination = '/data'
